---
# Configure openssh

- name: service is enabled and started
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  become: true
  loop: "{{ openssh_services_enable }}"
  when: openssh_enable_service
