---
# Install openssh packages

- name: unwanted packages are removed
  package:
    name: "{{ openssh_packages_remove }}"
    state: absent
  become: true
  when: openssh_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ openssh_packages_repos }}"
    state: "{{ openssh_packages_state }}"
  become: true

- name: prereq packages are installed
  package:
    name: "{{ openssh_packages_prereq }}"
    state: "{{ openssh_packages_state }}"
  become: true

- name: packages are installed
  package:
    name: "{{ openssh_packages_install }}"
    state: "{{ openssh_packages_state }}"
  become: true
